version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://db_user:db_password@db:5432/db_name

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  # Montage du répertoire contenant le script SQL
